paths:
  train_csv: student_resource/dataset/train.csv
  test_csv: student_resource/dataset/test.csv
  train_images: student_resource/train_images
  test_images: student_resource/test_images
  artifacts: artifacts
  submission: test_out.csv
  text_embeddings: artifacts/text_embeddings.npy
  image_embeddings: artifacts/image_embeddings.npy

model:
  text_embedding_model: all-MiniLM-L6-v2
  image_size: [128, 128]

training:
  n_splits: 5
  lgbm_params:
    random_state: 42
    n_estimators: 2000
    learning_rate: 0.02
    num_leaves: 31
    n_jobs: -1
